# Python の標準ライブラリを含めるためのダミーのインポート処理

def _import():

    import __future__
    import __phello__.foo
    import _abcoll
    import _LWPCookieJar
    import _MozillaCookieJar
    import _pyio
    import _strptime
    import _threading_local
    import _weakrefset
    import abc
    import aifc
    import antigravity
    import anydbm
    import argparse
    import ast
    import asynchat
    import asyncore
    import atexit
    import audiodev
    import base64
    import BaseHTTPServer
    import Bastion
    import bdb
    import binhex
    import bisect
    import calendar
    import cgi
    import CGIHTTPServer
    import cgitb
    import chunk
    import cmd
    import code
    import codecs
    import codeop
    import collections
    import colorsys
    import commands
    import compileall
    import ConfigParser
    import contextlib
    import Cookie
    import cookielib
    import copy
    import copy_reg
    import cProfile
    import csv
    import dbhash
    import decimal
    import difflib
    import dircache
    import dis
    import doctest
    import DocXMLRPCServer
    import dumbdbm
    import dummy_thread
    import dummy_threading
    import filecmp
    import fileinput
    import fnmatch
    import formatter
    import fpformat
    import fractions
    import ftplib
    import functools
    import genericpath
    import getopt
    import getpass
    import gettext
    import glob
    import gzip
    import hashlib
    import heapq
    import hmac
    import htmlentitydefs
    import htmllib
    import HTMLParser
    import httplib
    import ihooks
    import imaplib
    import imghdr
    import imputil
    import inspect
    import io
    import keyword
    import linecache
    import locale
    import macpath
    import macurl2path
    import mailbox
    import mailcap
    import markupbase
    import md5
    import mhlib
    import mimetools
    import mimetypes
    import MimeWriter
    import mimify
    import modulefinder
    import multifile
    import mutex
    import netrc
    import new
    import nntplib
    import ntpath
    import nturl2path
    import numbers
    import opcode
    import optparse
    import os
    import os2emxpath
    import pdb
    import pickle
    import pickletools
    import pipes
    import pkgutil
    import platform
    import plistlib
    import popen2
    import poplib
    import posixfile
    import posixpath
    import pprint
    import profile
    import pstats
    import pty
    import py_compile
    import pyclbr
    import pydoc
    import Queue
    import quopri
    import random
    import re
    import repr
    import rexec
    import rfc822
    import rlcompleter
    import robotparser
    import runpy
    import sched
    import sets
    import sgmllib
    import sha
    import shelve
    import shlex
    import shutil
    import SimpleHTTPServer
    import SimpleXMLRPCServer
    import site
    import smtpd
    import smtplib
    import sndhdr
    import socket
    import SocketServer
    import sre
    import sre_compile
    import sre_constants
    import sre_parse
    import ssl
    import stat
    import statvfs
    import string
    import StringIO
    import stringold
    import stringprep
    import struct
    import subprocess
    import sunau
    import sunaudio
    import symbol
    import symtable
    import sysconfig
    import tabnanny
    import tarfile
    import telnetlib
    import tempfile
    import textwrap
    import this
    import threading
    import timeit
    import toaiff
    import token
    import tokenize
    import trace
    import traceback
    import tty
    import types
    import urllib
    import urllib2
    import urlparse
    import user
    import UserDict
    import UserList
    import UserString
    import uu
    import uuid
    import warnings
    import wave
    import weakref
    import webbrowser
    import whichdb
    import xdrlib
    import xmllib
    import xmlrpclib
    import zipfile

    import bsddb
    import bsddb.db
    import bsddb.dbobj
    import bsddb.dbrecio
    import bsddb.dbshelve
    import bsddb.dbtables
    import bsddb.dbutils
    import compiler
    import compiler.ast
    import compiler.consts
    import compiler.future
    import compiler.misc
    import compiler.pyassem
    import compiler.pycodegen
    import compiler.symbols
    import compiler.syntax
    import compiler.transformer
    import compiler.visitor
    import ctypes
    import ctypes._endian
    import ctypes.macholib
    import ctypes.macholib.dyld
    import ctypes.macholib.dylib
    import ctypes.macholib.framework
    import ctypes.util
    import ctypes.wintypes
    import curses
    import curses.ascii
    import curses.has_key
    import curses.panel
    import curses.textpad
    import curses.wrapper
    import distutils
    import distutils.archive_util
    import distutils.bcppcompiler
    import distutils.ccompiler
    import distutils.cmd
    import distutils.command
    import distutils.command.bdist
    import distutils.command.bdist_dumb
    import distutils.command.bdist_msi
    import distutils.command.bdist_rpm
    import distutils.command.bdist_wininst
    import distutils.command.build
    import distutils.command.build_clib
    import distutils.command.build_ext
    import distutils.command.build_py
    import distutils.command.build_scripts
    import distutils.command.check
    import distutils.command.clean
    import distutils.command.config
    import distutils.command.install
    import distutils.command.install_data
    import distutils.command.install_egg_info
    import distutils.command.install_headers
    import distutils.command.install_lib
    import distutils.command.install_scripts
    import distutils.command.register
    import distutils.command.sdist
    import distutils.command.upload
    import distutils.config
    import distutils.core
    import distutils.cygwinccompiler
    import distutils.debug
    import distutils.dep_util
    import distutils.dir_util
    import distutils.dist
    import distutils.emxccompiler
    import distutils.errors
    import distutils.extension
    import distutils.fancy_getopt
    import distutils.file_util
    import distutils.filelist
    import distutils.log
    import distutils.msvc9compiler
    import distutils.msvccompiler
    import distutils.spawn
    import distutils.sysconfig
    import distutils.text_file
    import distutils.unixccompiler
    import distutils.util
    import distutils.version
    import distutils.versionpredicate
    import email
    import email._parseaddr
    import email.base64mime
    import email.charset
    import email.encoders
    import email.errors
    import email.feedparser
    import email.generator
    import email.header
    import email.iterators
    import email.message
    import email.mime
    import email.mime.application
    import email.mime.audio
    import email.mime.base
    import email.mime.image
    import email.mime.message
    import email.mime.multipart
    import email.mime.nonmultipart
    import email.mime.text
    import email.parser
    import email.quoprimime
    import email.utils
    import encodings
    import encodings.aliases
    import encodings.ascii
    import encodings.base64_codec
    import encodings.big5
    import encodings.big5hkscs
    import encodings.bz2_codec
    import encodings.charmap
    import encodings.cp037
    import encodings.cp1006
    import encodings.cp1026
    import encodings.cp1140
    import encodings.cp1250
    import encodings.cp1251
    import encodings.cp1252
    import encodings.cp1253
    import encodings.cp1254
    import encodings.cp1255
    import encodings.cp1256
    import encodings.cp1257
    import encodings.cp1258
    import encodings.cp424
    import encodings.cp437
    import encodings.cp500
    import encodings.cp720
    import encodings.cp737
    import encodings.cp775
    import encodings.cp850
    import encodings.cp852
    import encodings.cp855
    import encodings.cp856
    import encodings.cp857
    import encodings.cp858
    import encodings.cp860
    import encodings.cp861
    import encodings.cp862
    import encodings.cp863
    import encodings.cp864
    import encodings.cp865
    import encodings.cp866
    import encodings.cp869
    import encodings.cp874
    import encodings.cp875
    import encodings.cp932
    import encodings.cp949
    import encodings.cp950
    import encodings.euc_jis_2004
    import encodings.euc_jisx0213
    import encodings.euc_jp
    import encodings.euc_kr
    import encodings.gb18030
    import encodings.gb2312
    import encodings.gbk
    import encodings.hex_codec
    import encodings.hp_roman8
    import encodings.hz
    import encodings.idna
    import encodings.iso2022_jp
    import encodings.iso2022_jp_1
    import encodings.iso2022_jp_2
    import encodings.iso2022_jp_2004
    import encodings.iso2022_jp_3
    import encodings.iso2022_jp_ext
    import encodings.iso2022_kr
    import encodings.iso8859_1
    import encodings.iso8859_10
    import encodings.iso8859_11
    import encodings.iso8859_13
    import encodings.iso8859_14
    import encodings.iso8859_15
    import encodings.iso8859_16
    import encodings.iso8859_2
    import encodings.iso8859_3
    import encodings.iso8859_4
    import encodings.iso8859_5
    import encodings.iso8859_6
    import encodings.iso8859_7
    import encodings.iso8859_8
    import encodings.iso8859_9
    import encodings.johab
    import encodings.koi8_r
    import encodings.koi8_u
    import encodings.latin_1
    import encodings.mac_arabic
    import encodings.mac_centeuro
    import encodings.mac_croatian
    import encodings.mac_cyrillic
    import encodings.mac_farsi
    import encodings.mac_greek
    import encodings.mac_iceland
    import encodings.mac_latin2
    import encodings.mac_roman
    import encodings.mac_romanian
    import encodings.mac_turkish
    import encodings.mbcs
    import encodings.palmos
    import encodings.ptcp154
    import encodings.punycode
    import encodings.quopri_codec
    import encodings.raw_unicode_escape
    import encodings.rot_13
    import encodings.shift_jis
    import encodings.shift_jis_2004
    import encodings.shift_jisx0213
    import encodings.string_escape
    import encodings.tis_620
    import encodings.undefined
    import encodings.unicode_escape
    import encodings.unicode_internal
    import encodings.utf_16
    import encodings.utf_16_be
    import encodings.utf_16_le
    import encodings.utf_32
    import encodings.utf_32_be
    import encodings.utf_32_le
    import encodings.utf_7
    import encodings.utf_8
    import encodings.utf_8_sig
    import encodings.uu_codec
    import encodings.zlib_codec
    import hotshot
    import hotshot.log
    import hotshot.stats
    import hotshot.stones
    import idlelib
    import idlelib.aboutDialog
    import idlelib.AutoComplete
    import idlelib.AutoCompleteWindow
    import idlelib.AutoExpand
    import idlelib.Bindings
    import idlelib.CallTips
    import idlelib.CallTipWindow
    import idlelib.ClassBrowser
    import idlelib.CodeContext
    import idlelib.ColorDelegator
    import idlelib.configDialog
    import idlelib.configHandler
    import idlelib.configHelpSourceEdit
    import idlelib.configSectionNameDialog
    import idlelib.Debugger
    import idlelib.Delegator
    import idlelib.dynOptionMenuWidget
    import idlelib.EditorWindow
    import idlelib.FileList
    import idlelib.FormatParagraph
    import idlelib.GrepDialog
    import idlelib.HyperParser
    import idlelib.idle
    import idlelib.IdleHistory
    import idlelib.idlever
    import idlelib.IOBinding
    import idlelib.keybindingDialog
    import idlelib.macosxSupport
    import idlelib.MultiCall
    import idlelib.MultiStatusBar
    import idlelib.ObjectBrowser
    import idlelib.OutputWindow
    import idlelib.ParenMatch
    import idlelib.PathBrowser
    import idlelib.Percolator
    import idlelib.PyParse
    import idlelib.PyShell
    import idlelib.RemoteDebugger
    import idlelib.RemoteObjectBrowser
    import idlelib.ReplaceDialog
    import idlelib.rpc
    import idlelib.RstripExtension
    import idlelib.run
    import idlelib.ScriptBinding
    import idlelib.ScrolledList
    import idlelib.SearchDialog
    import idlelib.SearchDialogBase
    import idlelib.SearchEngine
    import idlelib.StackViewer
    import idlelib.tabbedpages
    import idlelib.testcode
    import idlelib.textView
    import idlelib.ToolTip
    import idlelib.TreeWidget
    import idlelib.UndoDelegator
    import idlelib.WidgetRedirector
    import idlelib.WindowList
    import idlelib.ZoomHeight
    import importlib
    import json
    import json.decoder
    import json.encoder
    import json.scanner
    import json.tool
    import logging
    import logging.config
    import logging.handlers
    import msilib
    import msilib.schema
    import msilib.sequence
    import msilib.text
    import multiprocessing
    import multiprocessing.connection
    import multiprocessing.dummy
    import multiprocessing.dummy.connection
    import multiprocessing.forking
    import multiprocessing.heap
    import multiprocessing.managers
    import multiprocessing.pool
    import multiprocessing.process
    import multiprocessing.queues
    import multiprocessing.reduction
    import multiprocessing.sharedctypes
    import multiprocessing.synchronize
    import multiprocessing.util
    import pydoc_data
    import pydoc_data.topics
    import sqlite3
    import sqlite3.dbapi2
    import sqlite3.dump
    import wsgiref
    import wsgiref.handlers
    import wsgiref.headers
    import wsgiref.simple_server
    import wsgiref.util
    import wsgiref.validate
    import xml
    import xml.dom
    import xml.dom.domreg
    import xml.dom.expatbuilder
    import xml.dom.minicompat
    import xml.dom.minidom
    import xml.dom.NodeFilter
    import xml.dom.pulldom
    import xml.dom.xmlbuilder
    import xml.etree
    import xml.etree.cElementTree
    import xml.etree.ElementInclude
    import xml.etree.ElementPath
    import xml.etree.ElementTree
    import xml.parsers
    import xml.parsers.expat
    import xml.sax
    import xml.sax._exceptions
    import xml.sax.expatreader
    import xml.sax.handler
    import xml.sax.saxutils
    import xml.sax.xmlreader

    import comtypes


